# Generated by Django 5.2.8 on 2025-12-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.URLField(default='https://dummyimage.com/150x150/cccccc/000000.png&text=No+Image'),
        ),
    ]
