# Generated by Django 5.2.8 on 2025-12-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_ticket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='commentaire',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='headline',
            new_name='titre',
        ),
    ]
